### ISSUE TITLE
line 135  can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by trivarialthea** [kac89/vulnrepo-json-to-latex-pdf#1]
Hi, i put the export in the input folder, but i am getting this error (Python 3.11.3):

line 135:

    issues = issues + """
             ^^^^^^^^^^^^
TypeError: can only concatenate str (not "list") to str

**Comment by kac89** [comment]
Hi,

Thanks for report. Can you maybe share these json report? ofc anonymize everything.

**Comment by trivarialthea** [comment]
As it is just a dummy scan and a test report i can share it as a whole. Here you go: https://anonfiles.com/QeZezd46z4/TEST_REPORT_json (github does not support uploading json files)

**Comment by kac89** [comment]
Thanks, so is that input from openvas free version ?

**Comment by trivarialthea** [comment]
@kac89, correct

**Comment by kac89** [comment]
So your JSON have different structure something seems to have changed on the openvas side. 

What version are you using?
is it kali linux version? 
can you also share XML version of report from openvas?

Thanks :-)

**Comment by trivarialthea** [comment]
I am using this docker deployment (https://github.com/immauss/openvas)
GSA: Version 22.5.3

The xml you requested is [here](https://anonfiles.com/Sd93we5fz4/task_fce8a7c3_8258_4b1e_8278_76d2a608a819_xml)

**Comment by kac89** [comment]
Thank you!  I'll let you know when the FIX comes in.

**Comment by kac89** [comment]
Hi, I made changes. Try now again. 

steps:
1. Go to vulnrepo.com 
2. import openvas 9 results-*.xml file 
3. download JSON 
4. do `git clone https://github.com/kac89/vulnrepo-json-to-latex-pdf.git`
5. put vulnrepo report json to input folder on `vulnrepo-json-to-latex-pdf`
6. run `python generate_latex.py`

it works for me.

**Comment by trivarialthea** [comment]
That seems to have fixed it!
